// GENERATED by codeblocks.js/art/Tiles/build_tilemap.py from tilemap.json - do not edit.
package de.fau.tf.lgdv.tilemap;

/**
 * Names of the built-in sprite animations for {@link MapSprite#play(String)}, e.g.
 * {@code snowman.play(Animation.MELT)}. Which sprite has which animation is listed at each
 * constant and in {@link SpriteType}.
 */
public final class Animation {
    private Animation() {}
    /** "burn": {@link SpriteType#FIRE} */
    public static final String BURN = "burn";
    /** "burnOut": {@link SpriteType#FIRE} */
    public static final String BURN_OUT = "burnOut";
    /** "burning": {@link SpriteType#FIRE} */
    public static final String BURNING = "burning";
    /** "calm": {@link SpriteType#VOLCANO} */
    public static final String CALM = "calm";
    /** "close": {@link SpriteType#BOOK} */
    public static final String CLOSE = "close";
    /** "closed": {@link SpriteType#BOOK} */
    public static final String CLOSED = "closed";
    /** "idle": {@link SpriteType#VOLCANO} */
    public static final String IDLE = "idle";
    /** "ignite": {@link SpriteType#FIRE} */
    public static final String IGNITE = "ignite";
    /** "lava": {@link SpriteType#VOLCANO} */
    public static final String LAVA = "lava";
    /** "loop": {@link SpriteType#ARROW}, {@link SpriteType#BOOK}, {@link SpriteType#DUCK_BROWN}, {@link SpriteType#DUCK_GREEN}, {@link SpriteType#DUCK_YELLOW}, {@link SpriteType#GRASS_WIND}, {@link SpriteType#GRASS_WIND_2}, {@link SpriteType#LEVEL_POINT_RED}, {@link SpriteType#LEVEL_POINT_YELLOW}, {@link SpriteType#SHARK}, {@link SpriteType#SHARK_SWIMMING}, {@link SpriteType#SHIPWRECK}, {@link SpriteType#VOLCANO}, {@link SpriteType#WATER_RIPPLES}, {@link SpriteType#WATER_RIPPLES_2} */
    public static final String LOOP = "loop";
    /** "melt": {@link SpriteType#SNOWMAN}, {@link SpriteType#SNOWMAN_XMAS} */
    public static final String MELT = "melt";
    /** "open": {@link SpriteType#BOOK} */
    public static final String OPEN = "open";
    /** "opened": {@link SpriteType#BOOK} */
    public static final String OPENED = "opened";
    /** "smoke": {@link SpriteType#VOLCANO} */
    public static final String SMOKE = "smoke";
    /** "snowing": {@link SpriteType#SNOW} */
    public static final String SNOWING = "snowing";
    /** "sparks": {@link SpriteType#VOLCANO} */
    public static final String SPARKS = "sparks";
}
