// GENERATED by codeblocks.js/art/Tiles/build_tilemap.py from tilemap.json - do not edit.
package de.fau.tf.lgdv.tilemap;

/** The characters that can be moved with a {@link MapCharacter}. */
public enum CharacterType {
    /** Walking character. Moves on land. */
    HERO(false, 4.0),
    /** Sailing ship (MS Floating Point), keeps rocking when idle. Moves on water. */
    SHIP(true, 2.5);

    /** {@code true}: moves on water, {@code false}: moves on land. */
    public final boolean onWater;
    /** Default speed in tiles per second. */
    public final double speed;

    CharacterType(boolean onWater, double speed) {
        this.onWater = onWater;
        this.speed = speed;
    }

    /** {@code true} if this character may enter a cell with the given terrain tile. */
    public boolean canEnter(int terrain) {
        return onWater ? Terrain.isWater(terrain) : Terrain.isLand(terrain);
    }
}
