// GENERATED by codeblocks.js/art/Tiles/build_tilemap.py from tilemap.json - do not edit.
package de.fau.tf.lgdv.tilemap;

/**
 * Decoration tiles for {@link TileMap#setDecorations(int[][])}: a second layer drawn on top of
 * the terrain. The values are the tile indices in the theme sheets. {@link #NONE} leaves a cell empty.
 *
 * <p>With auto tiling (default), {@link #PATH} connects to the neighbouring path tiles.</p>
 */
public final class Decoration {
    private Decoration() {}

    /** No decoration. */
    public static final int NONE = 0;
    /** Small ground details (grass tufts, ripples, ...) */
    public static final int GROUND_DETAIL_1 = 8;
    /** Small ground details */
    public static final int GROUND_DETAIL_2 = 9;
    /** Small ground details */
    public static final int GROUND_DETAIL_3 = 10;
    /** Small ground details */
    public static final int GROUND_DETAIL_4 = 11;
    /** Small ground details */
    public static final int GROUND_DETAIL_5 = 12;
    /** Axe */
    public static final int AXE = 13;
    /** Closed book */
    public static final int BOOK_CLOSED = 14;
    /** Animals (ducks, gull, snake, snowman) */
    public static final int ANIMAL_1 = 15;
    /** Dirt path connected to N, S */
    public static final int PATH_N_S = 16;
    /** Dirt path connected to E, W */
    public static final int PATH_E_W = 17;
    /** Dirt path connected to S */
    public static final int PATH_S = 18;
    /** Dirt path connected to W */
    public static final int PATH_W = 19;
    /** Flowers (footprints in the snow theme) */
    public static final int FLOWERS_1 = 28;
    /** Flowers */
    public static final int FLOWERS_2 = 29;
    /** Flowers */
    public static final int FLOWERS_3 = 30;
    /** Flowers */
    public static final int FLOWERS_4 = 31;
    /** Debris */
    public static final int DEBRIS = 32;
    /** Log */
    public static final int LOG = 33;
    /** Open book */
    public static final int BOOK_OPEN = 34;
    /** Red dot */
    public static final int MARKER_RED = 35;
    /** Dirt path connected to E, S */
    public static final int PATH_E_S = 36;
    /** Dirt path connected to E, S, W */
    public static final int PATH_E_S_W = 37;
    /** Dirt path connected to S, W */
    public static final int PATH_S_W = 38;
    /** Dirt path connected to N */
    public static final int PATH_N = 39;
    /** Tree (palm, cactus, fir, depending on the theme) */
    public static final int TREE_1 = 48;
    /** Tree */
    public static final int TREE_2 = 49;
    /** Tree */
    public static final int TREE_3 = 50;
    /** Group of trees */
    public static final int TREES_1 = 51;
    /** Group of trees (penguins in the snow theme) */
    public static final int TREES_2 = 52;
    /** Small house */
    public static final int HOUSE = 53;
    /** Bush (birds, snake or snow drift, depending on the theme) */
    public static final int BUSH = 54;
    /** Yellow dot */
    public static final int MARKER_YELLOW = 55;
    /** Dirt path connected to N, E, S */
    public static final int PATH_N_E_S = 56;
    /** Dirt path. Auto tiling connects it to the neighbouring path tiles */
    public static final int PATH = 57;
    /** Dirt path connected to N, S, W */
    public static final int PATH_N_S_W = 58;
    /** Dirt path connected to E */
    public static final int PATH_E = 59;
    /** Dock at a coast to the west */
    public static final int DOCK = 69;
    /** Dock at a cliff to the north */
    public static final int DOCK_2 = 70;
    /** Rocks in the water */
    public static final int ROCKS_1 = 71;
    /** Small rock in the water */
    public static final int ROCK_1 = 72;
    /** House */
    public static final int HOUSE_2 = 73;
    /** House with a gate */
    public static final int HOUSE_3 = 74;
    /** Yellow arrow pointing down */
    public static final int MARKER_ARROW = 75;
    /** Dirt path connected to N, E */
    public static final int PATH_N_E = 76;
    /** Dirt path connected to N, E, W */
    public static final int PATH_N_E_W = 77;
    /** Dirt path connected to N, W */
    public static final int PATH_N_W = 78;
    /** Variant of tile 16 */
    public static final int PATH_N_S_ALT = 79;
    /** Rocks in the water */
    public static final int ROCKS_2 = 89;
    /** Rocks in the water */
    public static final int ROCKS_3 = 90;
    /** Small rocks in the water */
    public static final int ROCK_2 = 91;
    /** Small rock in the water */
    public static final int ROCK_3 = 92;
    /** Village, top left quarter (see SpriteType.VILLAGE) */
    public static final int VILLAGE_NW = 93;
    /** Village, top right quarter */
    public static final int VILLAGE_NE = 94;
    /** Castle, top left part (see SpriteType.CASTLE) */
    public static final int CASTLE_NW = 95;
    /** Castle, top middle part */
    public static final int CASTLE_N = 96;
    /** Castle, top right part */
    public static final int CASTLE_NE = 97;
    /** Animal */
    public static final int ANIMAL_2 = 98;
    /** Variant of tile 17 */
    public static final int PATH_E_W_ALT = 99;
    /** Rocks in the water */
    public static final int ROCKS_4 = 109;
    /** Rocks in the water */
    public static final int ROCKS_5 = 110;
    /** Small rocks in the water */
    public static final int ROCK_4 = 111;
    /** Small rock in the water */
    public static final int ROCK_5 = 112;
    /** Village, bottom left quarter */
    public static final int VILLAGE_SW = 113;
    /** Village, bottom right quarter */
    public static final int VILLAGE_SE = 114;
    /** Castle, bottom left part */
    public static final int CASTLE_SW = 115;
    /** Castle, bottom middle part */
    public static final int CASTLE_S = 116;
    /** Castle, bottom right part */
    public static final int CASTLE_SE = 117;
    /** Small animal */
    public static final int ANIMAL_3 = 118;
    /** Animal (a boat in the beach theme) */
    public static final int ANIMAL_4 = 119;
    /** Dotted route between level points */
    public static final int ROUTE_E_TO_NW = 126;
    /** Dotted route between level points */
    public static final int ROUTE_E_TO_SW = 127;
    /** Dotted route between level points */
    public static final int ROUTE_W_TO_SE = 128;
    /** Dotted route between level points */
    public static final int ROUTE_W_TO_NE = 129;
    /** Dotted route between level points */
    public static final int ROUTE_E_TO_NW_ALT = 130;
    /** Dotted route between level points */
    public static final int ROUTE_E_TO_SW_ALT = 131;
    /** Dotted route between level points */
    public static final int ROUTE_W_TO_SE_ALT = 132;
    /** Dotted route between level points */
    public static final int ROUTE_W_TO_NE_ALT = 133;
    /** Dotted route between level points */
    public static final int ROUTE_S_TO_NE = 134;
    /** Dotted route between level points */
    public static final int ROUTE_S_TO_NW = 135;
    /** Dotted route between level points */
    public static final int ROUTE_N_TO_SE = 136;
    /** Dotted route between level points */
    public static final int ROUTE_N_TO_SW = 137;
    /** Dotted route between level points */
    public static final int ROUTE_SW_TO_NE = 138;
    /** Dotted route between level points */
    public static final int ROUTE_SE_TO_NW = 139;
    /** Single dense cloud */
    public static final int CLOUD_DENSE_1 = 140;
    /** Part of a dense cloud area */
    public static final int CLOUD_DENSE_NW = 141;
    /** Part of a dense cloud area */
    public static final int CLOUD_DENSE_N = 142;
    /** Part of a dense cloud area */
    public static final int CLOUD_DENSE_NE = 143;
    /** Single dense cloud */
    public static final int CLOUD_DENSE_2 = 144;
    /** Single medium cloud */
    public static final int CLOUD_MEDIUM_1 = 145;
    /** Part of a medium cloud area */
    public static final int CLOUD_MEDIUM_NW = 146;
    /** Part of a medium cloud area */
    public static final int CLOUD_MEDIUM_N = 147;
    /** Part of a medium cloud area */
    public static final int CLOUD_MEDIUM_NE = 148;
    /** Single medium cloud */
    public static final int CLOUD_MEDIUM_2 = 149;
    /** Single light cloud */
    public static final int CLOUD_LIGHT_1 = 150;
    /** Part of a light cloud area */
    public static final int CLOUD_LIGHT_NW = 151;
    /** Part of a light cloud area */
    public static final int CLOUD_LIGHT_N = 152;
    /** Part of a light cloud area */
    public static final int CLOUD_LIGHT_NE = 153;
    /** Single light cloud */
    public static final int CLOUD_LIGHT_2 = 154;
    /** Dotted route between level points */
    public static final int ROUTE_S_E = 155;
    /** Dotted route between level points */
    public static final int ROUTE_W_E = 156;
    /** Dotted route between level points */
    public static final int ROUTE_W_S = 157;
    /** Dotted route between level points */
    public static final int ROUTE_NW_TO_SE = 158;
    /** Dotted route between level points */
    public static final int ROUTE_NE_TO_SW = 159;
    /** Part of a dense cloud area */
    public static final int CLOUD_DENSE_W = 161;
    /** Part of a dense cloud area */
    public static final int CLOUD_DENSE_CENTER = 162;
    /** Part of a dense cloud area */
    public static final int CLOUD_DENSE_E = 163;
    /** Part of a medium cloud area */
    public static final int CLOUD_MEDIUM_W = 166;
    /** Part of a medium cloud area */
    public static final int CLOUD_MEDIUM_CENTER = 167;
    /** Part of a medium cloud area */
    public static final int CLOUD_MEDIUM_E = 168;
    /** Part of a light cloud area */
    public static final int CLOUD_LIGHT_W = 171;
    /** Part of a light cloud area */
    public static final int CLOUD_LIGHT_CENTER = 172;
    /** Part of a light cloud area */
    public static final int CLOUD_LIGHT_E = 173;
    /** Dotted route between level points */
    public static final int ROUTE_N_S = 175;
    /** Anchored ship */
    public static final int SHIP = 176;
    /** Dotted route between level points */
    public static final int ROUTE_N_S_ALT = 177;
    /** Dotted route between level points */
    public static final int ROUTE_S_TO_NE_ALT = 178;
    /** Dotted route between level points */
    public static final int ROUTE_S_TO_NW_ALT = 179;
    /** Single dense cloud */
    public static final int CLOUD_DENSE_3 = 180;
    /** Part of a dense cloud area */
    public static final int CLOUD_DENSE_SW = 181;
    /** Part of a dense cloud area */
    public static final int CLOUD_DENSE_S = 182;
    /** Part of a dense cloud area */
    public static final int CLOUD_DENSE_SE = 183;
    /** Single dense cloud */
    public static final int CLOUD_DENSE_4 = 184;
    /** Single medium cloud */
    public static final int CLOUD_MEDIUM_3 = 185;
    /** Part of a medium cloud area */
    public static final int CLOUD_MEDIUM_SW = 186;
    /** Part of a medium cloud area */
    public static final int CLOUD_MEDIUM_S = 187;
    /** Part of a medium cloud area */
    public static final int CLOUD_MEDIUM_SE = 188;
    /** Single medium cloud */
    public static final int CLOUD_MEDIUM_4 = 189;
    /** Single light cloud */
    public static final int CLOUD_LIGHT_3 = 190;
    /** Part of a light cloud area */
    public static final int CLOUD_LIGHT_SW = 191;
    /** Part of a light cloud area */
    public static final int CLOUD_LIGHT_S = 192;
    /** Part of a light cloud area */
    public static final int CLOUD_LIGHT_SE = 193;
    /** Single light cloud */
    public static final int CLOUD_LIGHT_4 = 194;
    /** Dotted route between level points */
    public static final int ROUTE_N_E = 195;
    /** Dotted route between level points */
    public static final int ROUTE_W_E_ALT = 196;
    /** Dotted route between level points */
    public static final int ROUTE_N_W = 197;
    /** Dotted route between level points */
    public static final int ROUTE_N_TO_SE_ALT = 198;
    /** Dotted route between level points */
    public static final int ROUTE_N_TO_SW_ALT = 199;
}
