// GENERATED by codeblocks.js/art/Tiles/build_tilemap.py from tilemap.json - do not edit.
package de.fau.tf.lgdv.tilemap;

/**
 * Everything that can be shown with a {@link MapSprite}: static objects from the theme sheet
 * (trees, houses, the village, the castle, ...) and animated sprites (volcano, arrow, ducks, ...).
 */
public enum SpriteType {
    /** Volcano with smoke, sparks and lava. Animations: "idle", "lava", "loop", "smoke", "sparks" (default "smoke") */
    VOLCANO(5, 4, true),
    /** Bouncing arrow. Animations: "loop" (default "loop") */
    ARROW(1, 1, true),
    /** Flashing red level point. Animations: "loop" (default "loop") */
    LEVEL_POINT_RED(1, 1, true),
    /** Flashing yellow level point. Animations: "loop" (default "loop") */
    LEVEL_POINT_YELLOW(1, 1, true),
    /** Book (glossary) that opens and closes. Animations: "close", "closed", "loop", "open", "opened" (default "closed") */
    BOOK(2, 1, true),
    /** Brown duck. Animations: "loop" (default "loop") */
    DUCK_BROWN(1, 1, true),
    /** Green duck. Animations: "loop" (default "loop") */
    DUCK_GREEN(1, 1, true),
    /** Yellow duckling. Animations: "loop" (default "loop") */
    DUCK_YELLOW(1, 1, true),
    /** Shark fin. Animations: "loop" (default "loop") */
    SHARK(1, 1, true),
    /** Shark swimming from left to right. Animations: "loop" (default "loop") */
    SHARK_SWIMMING(4, 1, true),
    /** Shipwreck. Animations: "loop" (default "loop") */
    SHIPWRECK(1, 1, true),
    /** Grass moving in the wind. Animations: "loop" (default "loop") */
    GRASS_WIND(1, 1, true),
    /** Grass moving in the wind. Animations: "loop" (default "loop") */
    GRASS_WIND_2(1, 1, true),
    /** Ripples on the water. Animations: "loop" (default "loop") */
    WATER_RIPPLES(1, 1, true),
    /** Ripples on the water. Animations: "loop" (default "loop") */
    WATER_RIPPLES_2(1, 1, true),
    /** Village (2 x 2 tiles) */
    VILLAGE(2, 2, false),
    /** Castle (3 x 2 tiles) */
    CASTLE(3, 2, false),
    /** Small ground details (grass tufts, ripples, ...) */
    GROUND_DETAIL_1(1, 1, false),
    /** Small ground details */
    GROUND_DETAIL_2(1, 1, false),
    /** Small ground details */
    GROUND_DETAIL_3(1, 1, false),
    /** Small ground details */
    GROUND_DETAIL_4(1, 1, false),
    /** Small ground details */
    GROUND_DETAIL_5(1, 1, false),
    /** Flowers (footprints in the snow theme) */
    FLOWERS_1(1, 1, false),
    /** Flowers */
    FLOWERS_2(1, 1, false),
    /** Flowers */
    FLOWERS_3(1, 1, false),
    /** Flowers */
    FLOWERS_4(1, 1, false),
    /** Tree (palm, cactus, fir, depending on the theme) */
    TREE_1(1, 1, false),
    /** Tree */
    TREE_2(1, 1, false),
    /** Tree */
    TREE_3(1, 1, false),
    /** Group of trees */
    TREES_1(1, 1, false),
    /** Group of trees (penguins in the snow theme) */
    TREES_2(1, 1, false),
    /** Bush (birds, snake or snow drift, depending on the theme) */
    BUSH(1, 1, false),
    /** Animals (ducks, gull, snake, snowman) */
    ANIMAL_1(1, 1, false),
    /** Animal */
    ANIMAL_2(1, 1, false),
    /** Small animal */
    ANIMAL_3(1, 1, false),
    /** Animal (a boat in the beach theme) */
    ANIMAL_4(1, 1, false),
    /** Axe */
    AXE(1, 1, false),
    /** Log */
    LOG(1, 1, false),
    /** Closed book */
    BOOK_CLOSED(1, 1, false),
    /** Open book */
    BOOK_OPEN(1, 1, false),
    /** Debris */
    DEBRIS(1, 1, false),
    /** Red dot */
    MARKER_RED(1, 1, false),
    /** Yellow dot */
    MARKER_YELLOW(1, 1, false),
    /** Yellow arrow pointing down */
    MARKER_ARROW(1, 1, false),
    /** Small house */
    HOUSE(1, 1, false),
    /** House */
    HOUSE_2(1, 1, false),
    /** House with a gate */
    HOUSE_3(1, 1, false),
    /** Dock at a coast to the west */
    DOCK(1, 1, false),
    /** Dock at a cliff to the north */
    DOCK_2(1, 1, false),
    /** Anchored ship */
    SHIP(1, 1, false),
    /** Rocks in the water */
    ROCKS_1(1, 1, false),
    /** Rocks in the water */
    ROCKS_2(1, 1, false),
    /** Rocks in the water */
    ROCKS_3(1, 1, false),
    /** Rocks in the water */
    ROCKS_4(1, 1, false),
    /** Rocks in the water */
    ROCKS_5(1, 1, false),
    /** Small rock in the water */
    ROCK_1(1, 1, false),
    /** Small rocks in the water */
    ROCK_2(1, 1, false),
    /** Small rock in the water */
    ROCK_3(1, 1, false),
    /** Small rocks in the water */
    ROCK_4(1, 1, false),
    /** Small rock in the water */
    ROCK_5(1, 1, false);

    /** Number of tiles the sprite covers horizontally / vertically. */
    public final int columns, rows;
    /** {@code true} for sprites with an animation. */
    public final boolean animated;

    SpriteType(int columns, int rows, boolean animated) {
        this.columns = columns;
        this.rows = rows;
        this.animated = animated;
    }
}
