// GENERATED by codeblocks.js/art/Tiles/build_tilemap.py from tilemap.json - do not edit.
package de.fau.tf.lgdv.tilemap;

/**
 * Terrain tiles for {@link TileMap#setTerrain(int[][])}. The values are the tile indices in the
 * theme sheets (20 tiles per row), so every theme shows the same kind of tile for a value.
 *
 * <p>With auto tiling (default), {@link #WATER} is replaced by the coast tile that matches its
 * land neighbours. All other values are drawn as they are.</p>
 */
public final class Terrain {
    private Terrain() {}
    /** Plain ground (grass, sand or snow, depending on the theme) */
    public static final int LAND = 0;
    /** Plain water. Auto tiling turns it into the matching coast tile */
    public static final int WATER = 1;
    /** Water with small waves */
    public static final int WATER_WAVES = 2;
    /** Water with a shark fin */
    public static final int WATER_FIN = 3;
    /** Water with small waves */
    public static final int WATER_WAVES_2 = 4;
    /** Water with land at SE, SW */
    public static final int COAST_SE_SW = 5;
    /** Water with a small island */
    public static final int WATER_ISLAND = 6;
    /** Water with islets */
    public static final int WATER_ISLETS = 7;
    /** Variant of tile 62 */
    public static final int COAST_N_S_ALT = 20;
    /** Variant of tile 103 */
    public static final int COAST_SE_NW_ALT = 21;
    /** Water with land at S */
    public static final int COAST_S = 22;
    /** Variant of tile 101 */
    public static final int COAST_NE_SW_ALT = 23;
    /** Variant of tile 26 */
    public static final int COAST_NE_SE_SW_NW_ISLET = 24;
    /** Water with land at E, W */
    public static final int COAST_E_W = 25;
    /** Water with land at NE, SE, SW, NW */
    public static final int COAST_NE_SE_SW_NW = 26;
    /** Water with islets */
    public static final int WATER_ISLETS_2 = 27;
    /** Water with land at SE */
    public static final int COAST_SE = 40;
    /** Water with land at E, S */
    public static final int COAST_E_S = 41;
    /** Water with land at N, E, S, W */
    public static final int COAST_N_E_S_W = 42;
    /** Water with land at S, W */
    public static final int COAST_S_W = 43;
    /** Water with land at SW */
    public static final int COAST_SW = 44;
    /** Water with land at NE, NW */
    public static final int COAST_NE_NW = 45;
    /** Water with land at E, S, W */
    public static final int COAST_E_S_W = 46;
    /** Water with an islet */
    public static final int WATER_ISLETS_3 = 47;
    /** Water with land at E */
    public static final int COAST_E = 60;
    /** Water with land at N, S, W */
    public static final int COAST_N_S_W = 61;
    /** Water with land at N, S */
    public static final int COAST_N_S = 62;
    /** Water with land at N, E, S */
    public static final int COAST_N_E_S = 63;
    /** Water with land at W */
    public static final int COAST_W = 64;
    /** Ground with a target marker */
    public static final int LAND_TARGET = 65;
    /** Water with land at E, S, NW */
    public static final int COAST_E_S_NW = 66;
    /** Water with land at S, W, NE */
    public static final int COAST_S_W_NE = 67;
    /** Water with islets */
    public static final int WATER_ISLETS_4 = 68;
    /** Water with land at NE */
    public static final int COAST_NE = 80;
    /** Water with land at N, E */
    public static final int COAST_N_E = 81;
    /** Water with land at N, E, W */
    public static final int COAST_N_E_W = 82;
    /** Water with land at N, W */
    public static final int COAST_N_W = 83;
    /** Water with land at NW */
    public static final int COAST_NW = 84;
    /** Ground with a trail leading down to the water (place water below it) */
    public static final int LAND_TRAIL = 85;
    /** Water with land at N, E, SW */
    public static final int COAST_N_E_SW = 86;
    /** Water with land at N, W, SE */
    public static final int COAST_N_W_SE = 87;
    /** Water with islets */
    public static final int WATER_ISLETS_5 = 88;
    /** Water with land at NE, SE */
    public static final int COAST_NE_SE = 100;
    /** Water with land at NE, SW */
    public static final int COAST_NE_SW = 101;
    /** Water with land at N */
    public static final int COAST_N = 102;
    /** Water with land at SE, NW */
    public static final int COAST_SE_NW = 103;
    /** Water with land at SW, NW */
    public static final int COAST_SW_NW = 104;
    /** End of the trail of LAND_TRAIL in the water */
    public static final int WATER_TRAIL = 105;
    /** Water with islets */
    public static final int WATER_ISLETS_6 = 106;
    /** Water with islets */
    public static final int WATER_ISLETS_7 = 107;
    /** Water with a small island and a rock */
    public static final int WATER_ISLAND_2 = 108;
    /** Water with land at N, SW */
    public static final int COAST_N_SW = 120;
    /** Water with land at N, SE, SW */
    public static final int COAST_N_SE_SW = 121;
    /** Water with land at N, SE */
    public static final int COAST_N_SE = 122;
    /** Water with land at S, NW */
    public static final int COAST_S_NW = 123;
    /** Water with land at S, NE, NW */
    public static final int COAST_S_NE_NW = 124;
    /** Water with land at S, NE */
    public static final int COAST_S_NE = 125;
    /** Water with land at E, SW */
    public static final int COAST_E_SW = 160;
    /** Water with land at W, NE */
    public static final int COAST_W_NE = 164;
    /** Water with land at W, SE */
    public static final int COAST_W_SE = 165;
    /** Water with land at E, NW */
    public static final int COAST_E_NW = 169;
    /** Water with land at W, NE, SE */
    public static final int COAST_W_NE_SE = 170;
    /** Water with land at E, SW, NW */
    public static final int COAST_E_SW_NW = 174;

    private static final boolean[] WATER_TILES = new boolean[200];
    static {
        for (int id : new int[] {1, 2, 3, 4, 5, 6, 7, 20, 21, 22, 23, 24, 25, 26, 27, 40, 41, 42, 43, 44, 45, 46, 47, 60, 61, 62, 63, 64, 66, 67, 68, 80, 81, 82, 83, 84, 86, 87, 88, 100, 101, 102, 103, 104, 105, 106, 107, 108, 120, 121, 122, 123, 124, 125, 160, 164, 165, 169, 170, 174}) WATER_TILES[id] = true;
    }

    /** {@code true} if the tile shows (mostly) water, i.e. a ship can sail there. */
    public static boolean isWater(int tile) {
        return tile >= 0 && tile < WATER_TILES.length && WATER_TILES[tile];
    }

    /** {@code true} if the tile is land, i.e. a walking character can go there. */
    public static boolean isLand(int tile) {
        return tile >= 0 && tile < WATER_TILES.length && !WATER_TILES[tile];
    }
}
