// GENERATED by codeblocks.js/art/Tiles/build_tilemap.py from tilemap.json - do not edit.
package de.fau.tf.lgdv.tilemap;

/** The look of a {@link TileMap}. All themes use the same tile layout. */
public enum Theme {
    /** Green valley with deciduous trees */
    VALLEY,
    /** Sandy beach with palm trees */
    BEACH,
    /** Desert with cacti */
    DESERT,
    /** Winter landscape with fir trees */
    SNOW;

    /** Name of the theme in tilemap.json. */
    public String id() {
        return name().toLowerCase();
    }
}
